version: '3.5'
services:
  php:
    build: .
    image: spryker-minimal-php
    container_name: ${PROJECT_NAME}-php
    env_file:
      - spryker.env
    volumes:
      - ../:/data/shop/development
      - ./spryker.conf:/etc/nginx/conf.d/yves_de_spryker.conf
    ports:
      - 8080:8080
      - 80:80
    networks:
      default:
        aliases:
          - "www.de.suite.local"
          - "zed.de.suite.local"
  redis:
    image: redis:3.2.11
    container_name: ${PROJECT_NAME}-redis
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
  postgres:
    image: postgres:9.4.16
    container_name: ${PROJECT_NAME}-postgres
    env_file:
      - spryker.env
    ports:
      - 5432:5432
  elasticsearch:
    image: elasticsearch:5.6.8
    container_name: ${PROJECT_NAME}-elasticsearch
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
  rabbitmq:
    image: rabbitmq:3.7.3-management
    container_name: ${PROJECT_NAME}-rabbitmq
    env_file:
      - spryker.env
    ports:
      - 15672:15672